### ISSUE TITLE
Does it work behind corporate proxy?

### ISSUE THREAD

**Issue by Toumash** [solid-company/interop-gus#1]
Does it work behind a proxy?
How can i configure it from asp.net core DI?

Minimal api sample here
```csharp
builder.Services.AddGusClient(c =>
{
    c.Environment = builder.Environment.IsProduction() ? GusEnironment.Production : GusEnironment.Test;
    c.Key = builder.Configuration["Integrations:Gus"];
});
```

Im getting

![image](https://user-images.githubusercontent.com/9840635/166921967-89d49d18-0885-4070-ac73-301f2e4c33e6.png)

**Comment by wojciech-torkowski** [comment]
I've added support for proxy connection - please check the latest NuGet package.

Please let me know if it works for you!

**Comment by Toumash** [comment]
> I've added support for proxy connection - please check the latest NuGet package.
> 
> Please let me know if it works for you!

Thanks for a quick response!
Not sure if the credentials passed by ProxyAddress Uri will work or if i need them, but i will check it out in on monday/wednesday.
I dont know a better way of disabling the internet access except through proxy on dev vm than by running on actual corporate environment 😅
